apiVersion: v1
kind: Service
metadata:
  name: hospital-api
  labels:
    app.kubernetes.io/name: hospital-api
    app.kubernetes.io/instance: release-name
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: hospital-api
    app.kubernetes.io/instance: release-name