apiVersion: v2
name: hospital-api
description: A Helm chart for Hospital API Spring Boot application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - spring
  - hospital
  - api
maintainers:
  - name: Hospital Team
    email: team@hospital.example.com