apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../feature-deployment.yaml

commonLabels:
  app.kubernetes.io/name: hospital-api
  app.kubernetes.io/part-of: hospital-system
  app.kubernetes.io/managed-by: kustomize
  environment: feature

namePrefix: feature-