-- Add sample data to clinical_records table
INSERT INTO clinical_records (id, patient_id, doctor_id, type, title, description, attachment_url, created_at, updated_at)
VALUES
    ('550e8400-e29b-41d4-a716-446655440000', 
     (SELECT id FROM patients LIMIT 1), 
     (SELECT id FROM medical_staff LIMIT 1), 
     'DIAGNOSIS', 
     'Initial Diagnosis', 
     'Patient presented with symptoms of common cold. Prescribed rest and fluids.', 
     NULL, 
     NOW(), 
     NOW()),
     
    ('550e8400-e29b-41d4-a716-446655440001', 
     (SELECT id FROM patients LIMIT 1), 
     (SELECT id FROM medical_staff LIMIT 1), 
     'PRESCRIPTION', 
     'Cold Medication', 
     'Prescribed cold medication for symptom relief. Take as directed.', 
     'https://example.com/prescriptions/123.pdf', 
     NOW(), 
     NOW()),
     
    ('550e8400-e29b-41d4-a716-446655440002', 
     (SELECT id FROM patients LIMIT 1 OFFSET 1), 
     (SELECT id FROM medical_staff LIMIT 1 OFFSET 1), 
     'LAB_RESULT', 
     'Blood Test Results', 
     'Blood test results show normal levels. No concerns at this time.', 
     'https://example.com/lab_results/456.pdf', 
     NOW(), 
     NOW()),
     
    ('550e8400-e29b-41d4-a716-446655440003', 
     (SELECT id FROM patients LIMIT 1 OFFSET 1), 
     (SELECT id FROM medical_staff LIMIT 1 OFFSET 1), 
     'VITAL_SIGNS', 
     'Routine Check-up', 
     'Blood pressure: 120/80, Heart rate: 72 bpm, Temperature: 98.6°F', 
     NULL, 
     NOW(), 
     NOW()),
     
    ('550e8400-e29b-41d4-a716-446655440004', 
     (SELECT id FROM patients LIMIT 1 OFFSET 2), 
     (SELECT id FROM medical_staff LIMIT 1 OFFSET 2), 
     'MEDICAL_HISTORY', 
     'Patient History Update', 
     'Updated patient history to include recent surgery and recovery.', 
     NULL, 
     NOW(), 
     NOW());