name: CD Feature Deployment

on:
  workflow_run:
    workflows: ["CI Common Tasks"]
    branches: [feature/*]
    types:
      - completed

jobs:
  deploy-to-feature:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2
        with:
          kustomize-version: "4.5.7"
      - name: Set Kubernetes context
        uses: azure/k8s-set-context@v3
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
      - name: Extract feature name
        id: extract-feature
        run: |
          FEATURE_NAME=$(echo ${{ github.ref }} | sed -e "s/refs\/heads\/feature\///")
          echo "::set-output name=feature_name::${FEATURE_NAME}"
      - name: Update image in kustomization
        run: |
          cd kubernetes/feature
          kustomize edit set image ${DOCKER_HUB_USERNAME}/hospital-api:latest=${{ secrets.DOCKER_HUB_USERNAME }}/hospital-api:latest
      - name: Deploy to Kubernetes
        run: |
          cd kubernetes/feature
          kustomize build | kubectl apply -f -
      - name: Verify deployment
        run: |
          kubectl rollout status deployment/hospital-api-feature -n default