name: CD Production Deployment

on:
  workflow_run:
    workflows: ["CI Common Tasks"]
    branches: [main]
    types:
      - completed

jobs:
  deploy-to-production:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2
        with:
          kustomize-version: "4.5.7"
      - name: Set Kubernetes context
        uses: azure/k8s-set-context@v3
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
      - name: Update image in kustomization
        run: |
          cd kubernetes/prod
          kustomize edit set image ${DOCKER_HUB_USERNAME}/hospital-api:latest=${{ secrets.DOCKER_HUB_USERNAME }}/hospital-api:latest
      - name: Deploy to Kubernetes
        run: |
          cd kubernetes/prod
          kustomize build | kubectl apply -f -
      - name: Verify deployment
        run: |
          kubectl rollout status deployment/hospital-api-prod -n default
      - name: Notify deployment completion
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: deployments
          SLACK_COLOR: good
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'Production deployment completed successfully :rocket:'
          SLACK_TITLE: Production Deployment
          SLACK_USERNAME: GitHub Actions